### ISSUE TITLE
elasticsearch as root

### ISSUE THREAD

**Issue by vap0rtranz** [ctron/simulating-iot#1]
The elasticsearch deploy complains that it is running as root.  I ran the deploy-kapua.sh script as developer, not admin, and I run minishift as non-root, so the container is running as root??  Log snippet is below.

My setup is Minishift via CDKv3.
```
]$ minishift version
Minishift version: 1.0.0+4f8cb6d
CDK Version: 3.0.0
]$ oc version
oc v3.5.5.8
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.30:8443
openshift v3.5.5.8
kubernetes v1.5.2+43a9be4
```

        
```
        [2017-06-13T21:55:07,318][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
        org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
        Caused by: java.lang.RuntimeException: can not run elasticsearch as root
```

**Comment by vap0rtranz** [comment]
Retried on OCP cluster (I can send you details directly if needed) and could not reproduce, so does indeed look like Minishift quirk, or my Minishift setup via CDK being borked.

```
$ oc version
oc v3.5.5.8
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server REDACTED
openshift v3.5.5.15
kubernetes v1.5.2+43a9be4

$ oc get pods
NAME                    READY     STATUS    RESTARTS   AGE
elasticsearch-1-q3x75   1/1       Running   0          3m
kapua-api-1-1z2s3       1/1       Running   0          3m
kapua-broker-1-h0142    1/1       Running   0          3m
kapua-console-1-n5wr5   1/1       Running   0          3m
sql-1-bqm9k             1/1       Running   0          3m
```

**Comment by ctron** [comment]
I am using minishift with OpenShift Origin 1.5 and don't run into this issue.

What makes me scratch my head is that I was under the impression that OpeShift would **not** run things as root.

Strange.

**Comment by vap0rtranz** [comment]
Since we can't reproduce in either Origin or OCP, then I'm going to write this off as how Minishift builds Openshift, and close it out.
